#!/bin/bash
set -e

# Create symlinks for easy access to scripts
ln -sf /usr/local/bin/dbibih/backup.sh /usr/local/bin/backup
ln -sf /usr/local/bin/dbibih/cleanup.sh /usr/local/bin/cleanup
ln -sf /usr/local/bin/dbibih/cpu_memory_check.sh /usr/local/bin/cpu_memory_check
ln -sf /usr/local/bin/dbibih/disk_check.sh /usr/local/bin/disk_check
ln -sf /usr/local/bin/dbibih/system_update.sh /usr/local/bin/system_update

exit 0
